### ISSUE TITLE
Package moontoast/math is abandoned, you should avoid using it. Use brick/math instead.

### ISSUE THREAD

**Issue by jonnott** [pascaldevink/shortuuid#68]
"Package moontoast/math is abandoned, you should avoid using it. Use brick/math instead."

.. is what composer now tells us when using this package :(

How hard is it to replace moontoast/math with brick/math? I'm not expert enough, but it seems like it shouldn't be too hard. brick/math has a BigNumber class also. Direct like-for-like swap?

**Comment by jonnott** [comment]
@pascaldevink

**Comment by pascaldevink** [comment]
It's not possible right now to remove it, as it is a dependency of `ramsey/uuid`, of which the latest stable version still depends on `moontoast/math`. However, with the upcoming 4.x release of that library, @ramsey updated that dependency as well, so the next major version of this library can remove that dependency

**Comment by jonnott** [comment]
> It's not possible right now to remove it, as it is a dependency of `ramsey/uuid`, of which the latest stable version still depends on `moontoast/math`. However, with the upcoming 4.x release of that library, @ramsey updated that dependency as well, so the next major version of this library can remove that dependency

It only actually appears in the 'require-dev' and 'suggest' sections of ramsey/uuid's composer.json (for the current version 3.9.2) - which suggests it's not actually required. Am I missing something?

https://github.com/ramsey/uuid/blob/7779489a47d443f845271badbdcedfe4df8e06fb/composer.json

**Comment by ramsey** [comment]
It's required if you want to do anything with the integers that make up the UUID.

There are other cases where it's required, as well. See this other thread I commented on earlier today: https://github.com/laravel/framework/issues/23291#issuecomment-573825311

**Comment by jonnott** [comment]
@ramsey @pascaldevink as ramsey/uuid 4.0 is out, can this all be resolved now?

**Comment by pascaldevink** [comment]
@jonnott I'll resolve it once I've tagged a new major version

**Comment by jonnott** [comment]
@pascaldevink @ramsey 

I'm not sure why I'm still getting the abandoned warning..?

```
  - Removing paragonie/random_compat (v9.99.99)
  - Installing ramsey/collection (1.0.1): Downloading (100%)
  - Installing brick/math (0.8.14): Downloading (100%)
  - Updating ramsey/uuid (3.9.3 => 4.0.0): Downloading (100%)
  - Updating pascaldevink/shortuuid (2.2.0 => 2.3.0): Downloading (100%)
Package moontoast/math is abandoned, you should avoid using it. Use brick/math instead.
```

**Comment by jonnott** [comment]
...can `"moontoast/math": "^1.1"` now be removed from the `require` section of composer.json ?

**Comment by ramsey** [comment]
> I'm not sure why I'm still getting the abandoned warning..?

You're getting the abandoned warning because the package is abandoned. This is just a warning. It is not an error.

Moontoast\Math\BigNumber is used in pascaldevink/shortuuid, so it cannot be removed from composer.json until the code is changed to use a different library. This is not a critical, high-priority issue.

**Comment by jonnott** [comment]
Ok, so I'm assuming [@pascaldevink] that the next major version, as well as dropping support for ramsey/uuid v3.x, will also drop the dependency on moontoast/math ?

**Comment by pascaldevink** [comment]
@jonnott yep, see #71

**Comment by pascaldevink** [comment]
Version 3.0 has just been released, which drops support for ramsey/uuid 3.x and moontoast/math. Thanks all for contributing to the discussion.
