### ISSUE TITLE
Short UUID could be only 20 characters long

### ISSUE THREAD

**Issue by OndraM** [pascaldevink/shortuuid#8]
Hi, in some cases, short UUID could be only 20 characters long.

For example for this UUID v4:
- 000d116f-802c-4e2f-8308-e1980dd99276 => dTWggwbeHLVsnWpCkzWX
- 0015c755-1251-4128-ac6b-5422e85cc0f3 => kQaxtinEYSekY5SNJ9Cs
- 000fe80f-32f6-4365-9d96-b7855fade5fc => mAweervpUg8fZmDePLvd
etc.

This could cause the tests to fail in some cases, becase the tests require the short UUID to be 21 or 22 chars long. To reproduce just call the test many times, like:
```php
    /**
     * @test
     */
    public function it_should_generate_a_short_uuid4()
    {
        for ($i = 0; $i < 10000; $i++) {
            $shortUuid = ShortUuid::uuid4();
            $this->assertLessThanOrEqual(22, strlen($shortUuid), $shortUuid);
            $this->assertGreaterThanOrEqual(21, strlen($shortUuid), $shortUuid);
        }
    }
```

I guess this is just an issue in the tests expectations, right? Ie. the short uuid actually can be 20 characters long.

**Comment by pascaldevink** [comment]
Good find! They seem to be valid uuid, so I adjusted the tests in https://github.com/pascaldevink/shortuuid/commit/9a91405f0062375f2a918ab4fa89d2d1391db7ab
